#' Bin LD values for decay plotting
#'
#' @param input A tibble generated by load_plink_ld
#' @param bin_size Size of bins, in bp, in which to calculate LD
#' @param stat Calculate decay for r2 or dp (dprime)?
#' @param max_dist Maximum distance between SNPs to allow.
#'
#' @return A tibble
#' @export
#'
#' @examples
#' a <- system.file("extdata", "test.plink.ld.gz", package = "gwplotting" )
#' b <- load_plink_ld( a, max_dist = 10000 )
#' c <- calculate_ld_decay( b, bin_size = 200 )
#' c
calculate_ld_decay <- function( input, bin_size = 200, max_dist = 50000,
                                stat = 'r2' ){

  # Don't need all that other stuff for genome-wide decay
  input <- dplyr::select( input, dist, stat ) %>%
    dplyr::filter( dist <= max_dist )

  # What happens when we're inconsistent?
  if( max_dist > max( input$dist ) ){
    warning(paste0("Your maximum allowed distance is set to a value greater than
            the maximum distance found in your input. Setting max_dist to
            ",max(input$dist)))
    max_dist <- max( input$dist, na.rm = T )
  }

  # Bin it
  input$bin <- ggplot2::cut_width( x = input$dist, width = bin_size,
                                   boundary = 0, closed = 'left' )

  # use standard evaluation summarize_
  todo <- paste0('mean(',stat,')')

  # Group and mean
  for_return <- input %>% dplyr::group_by( bin ) %>%
    dplyr::summarize_( mean_stat = todo )

  # Add a column for the max distance between SNPs in the bin
  for_return <- dplyr::mutate( for_return, position = bin ) %>%
    dplyr::mutate( position = stringr::str_replace( position, "\\[.*,","" )) %>%
    dplyr::mutate( position = as.numeric( stringr::str_replace( position, "\\)|\\]","" ))) %>%
    dplyr::select( position, mean_stat )


}
